include R:\workspace\makefile\watcom\makefile  
PROJECT = zcmd
TARGET_OS = dos
PROJECT_TYPE = exe
LIBS = xrzlib.lib
DIST_LIB = xrzlib.lib
DIST_INCLUDE = $(wildcard $(SOURCE_DIR)/*.h)
LOCAL_PREFIX = r:\workspace



