/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *vboxMain;
  GtkWidget *statusBar;
  GtkWidget *hbox1;
  GtkWidget *imageUri;
  GtkWidget *btnOpen;
  GtkWidget *scrolledwindow;
  GtkWidget *imgViewport;
  GtkWidget *hbox2;
  GtkWidget *imageBox;

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window, "window");
  gtk_container_set_border_width (GTK_CONTAINER (window), 2);
  gtk_window_set_title (GTK_WINDOW (window), _("BeautyOnline"));
  gtk_window_set_position (GTK_WINDOW (window), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window), 500, 400);
  gtk_window_set_icon_name (GTK_WINDOW (window), "stock_draw-sphere");
  gtk_window_set_urgency_hint (GTK_WINDOW (window), TRUE);

  vboxMain = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (vboxMain, "vboxMain");
  gtk_widget_show (vboxMain);
  gtk_container_add (GTK_CONTAINER (window), vboxMain);
  gtk_container_set_border_width (GTK_CONTAINER (vboxMain), 1);

  statusBar = gtk_statusbar_new ();
  gtk_widget_set_name (statusBar, "statusBar");
  gtk_widget_show (statusBar);
  gtk_box_pack_end (GTK_BOX (vboxMain), statusBar, FALSE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vboxMain), hbox1, FALSE, TRUE, 0);

  imageUri = gtk_entry_new ();
  gtk_widget_set_name (imageUri, "imageUri");
  gtk_widget_show (imageUri);
  gtk_box_pack_start (GTK_BOX (hbox1), imageUri, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (imageUri), 8226);

  btnOpen = gtk_button_new_with_mnemonic (_("Open"));
  gtk_widget_set_name (btnOpen, "btnOpen");
  gtk_widget_show (btnOpen);
  gtk_box_pack_start (GTK_BOX (hbox1), btnOpen, FALSE, FALSE, 0);

  scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow, "scrolledwindow");
  gtk_widget_show (scrolledwindow);
  gtk_box_pack_end (GTK_BOX (vboxMain), scrolledwindow, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  imgViewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (imgViewport, "imgViewport");
  gtk_widget_show (imgViewport);
  gtk_container_add (GTK_CONTAINER (scrolledwindow), imgViewport);

  hbox2 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (imgViewport), hbox2);

  imageBox = create_pixmap (window, NULL);
  gtk_widget_set_name (imageBox, "imageBox");
  gtk_widget_show (imageBox);
  gtk_box_pack_start (GTK_BOX (hbox2), imageBox, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (imageBox), 0, 0);

  g_signal_connect_swapped ((gpointer) imageUri, "activate",
                            G_CALLBACK (on_imageUri_activate),
                            GTK_OBJECT (imageBox));
  g_signal_connect_swapped ((gpointer) btnOpen, "clicked",
                            G_CALLBACK (on_btnOpen_clicked),
                            GTK_OBJECT (imageUri));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, vboxMain, "vboxMain");
  GLADE_HOOKUP_OBJECT (window, statusBar, "statusBar");
  GLADE_HOOKUP_OBJECT (window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window, imageUri, "imageUri");
  GLADE_HOOKUP_OBJECT (window, btnOpen, "btnOpen");
  GLADE_HOOKUP_OBJECT (window, scrolledwindow, "scrolledwindow");
  GLADE_HOOKUP_OBJECT (window, imgViewport, "imgViewport");
  GLADE_HOOKUP_OBJECT (window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window, imageBox, "imageBox");

  return window;
}

